In [1]:
from datasets import load_dataset
import pandas as pd

Диалоги агентов поддержки с клиентами, размечены по интентам. Используем для обучения базовому тону агента и покрытия сценариев отмены и жалоб

In [2]:
df = load_dataset("bitext/Bitext-customer-support-llm-chatbot-training-dataset")
df1 = df["train"].to_pandas()
df1.to_csv("bitext_support.csv", index=False)
print(df1.shape)
df1.head(3)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/11.9k [00:00<?, ?B/s]

Bitext_Sample_Customer_Support_Training_(…):   0%|          | 0.00/19.2M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/26872 [00:00<?, ? examples/s]

(26872, 5)

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...

Инструкции и ответы агента в телеком домене. Учим модель терминологии и стилю телеком-поддержки

In [3]:
df = load_dataset("akshayjambhulkar/customer-support-telecom-alpaca")
df1 = df["train"].to_pandas()
df1.to_csv("telecom_alpaca.csv", index=False)
print(df1.shape)
df1.head(3)

README.md:   0%|          | 0.00/343 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/14.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/116 [00:00<?, ? examples/s]

(116, 3)

,instruction,input,output
0,Can I use my mobile plan while traveling abroad?,,"Yes, you can use your mobile plan while travel..."
1,What is VoLTE and do you support it?,,"VoLTE stands for Voice over LTE, which allows ..."
2,How can I check network coverage in my area?,,You can check network coverage in your area by...

Диалоги с множественными хода в овтетах телеком-поддержки. Учим модель вести связный разговор, а не отвечать на одиночный вопрос

In [4]:
df = load_dataset("akshayjambhulkar/telecom-conversational-support-chat-pre-processed")
df1 = df["train"].to_pandas()
df1.to_csv("telecom_chat.csv", index=False)
print(df1.shape)
df1.head(3)

README.md:   0%|          | 0.00/341 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/209M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/228414 [00:00<?, ? examples/s]

(228414, 2)

,conversation_id,text
0,00000ecf65b04c5790f348e9455e790b,"Good day, thank you for reaching out to Union ..."
1,00004405b72d4e81908143e4427b41f3,"Good morning, thank you for calling Union Mobi..."
2,00005aa1d5704cf69dd295de02663eb5,"Hello, thank you for calling Union Mobile. My ..."

Реальные скрипты колл-центра. После фильтрации по словам cancel/churn/discount дает реальные сценарии возвращаемости клиентов

In [10]:
df = load_dataset("bitext/Bitext-customer-support-llm-chatbot-training-dataset")
df1 = df["train"].to_pandas()
intent = ["track_order", "delivery_options", "contact_human_agent","get_invoice",
          "check_invoice", "registration_problems", "payment_issue", "check_payment_methods"]
dffinal = df1[df1["intent"].isin(intent)].copy()
dffinal.to_csv("callcenter_scripts.csv", index=False)
print(dffinal.shape)
dffinal.head(3)

(7985, 5)

,flags,instruction,category,intent,response
3918,BZ,show me invoice{{Invoice Number}},INVOICE,check_invoice,I understand your need to locate your bill wit...
3919,BLMQZ,need to see my invoicesfrom {{Person Name}},INVOICE,check_invoice,Certainly! I understand that you are looking t...
3920,BCL,"I have to see my invoice from {{Person Name}},...",INVOICE,check_invoice,I'm on it! I understand your urgency to view t...

Диалоги убеждения, как один участник переубеждает другого. Учим модель логике возвращения клиента, то есть как аргументировать, предлагать альтернативы и удерживать

In [11]:
df = load_dataset("Anthropic/persuasion")
if "train" in df:
    item = "train"
else:
    item = list(df.keys())[0]
df_persuasion = df[item].to_pandas()
df_persuasion.to_csv("persuasion.csv", index=False)
print(df_persuasion.shape)
df_persuasion.head(3)

README.md:   0%|          | 0.00/1.74k [00:00<?, ?B/s]

persuasion_data.csv:   0%|          | 0.00/6.94M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3939 [00:00<?, ? examples/s]

(3939, 8)

,worker_id,claim,argument,source,prompt_type,rating_initial,rating_final,persuasiveness_metric
0,PQVTZECGNK3K,Governments and technology companies must do m...,It's time for governments and tech companies t...,Claude 2,Expert Writer Rhetorics,7 - Strongly support,7 - Strongly support,0
1,3KTT9HNPV9WX,Governments and technology companies must do m...,"In today's hyper-connected world, our personal...",Claude 3 Haiku,Expert Writer Rhetorics,7 - Strongly support,7 - Strongly support,0
2,M76GMRF46C69,Cultured/lab-grown meats should be allowed to ...,The future of food must include cultured/lab-g...,Claude 2,Compelling Case,3 - Somewhat oppose,5 - Somewhat support,2